### ISSUE TITLE
can u help me?

### ISSUE THREAD

**Issue by tiandaoyuxi** [gpt-omni/mini-omni#17]
(omni) D:\mini-omni>python server.py --ip '0.0.0.0' --port 60808

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "D:\mini-omni\server.py", line 6, in <module>
    from inference import OmniInference
  File "D:\mini-omni\inference.py", line 2, in <module>
    import lightning as L
  File "C:\Users\win11\.conda\envs\omni\lib\site-packages\lightning\__init__.py", line 18, in <module>
    from lightning.fabric.fabric import Fabric  # noqa: E402
  File "C:\Users\win11\.conda\envs\omni\lib\site-packages\lightning\fabric\__init__.py", line 30, in <module>
    from lightning.fabric.fabric import Fabric  # noqa: E402
  File "C:\Users\win11\.conda\envs\omni\lib\site-packages\lightning\fabric\fabric.py", line 35, in <module>
    import torch
  File "C:\Users\win11\.conda\envs\omni\lib\site-packages\torch\__init__.py", line 2120, in <module>
    from torch._higher_order_ops import cond
  File "C:\Users\win11\.conda\envs\omni\lib\site-packages\torch\_higher_order_ops\__init__.py", line 1, in <module>
    from .cond import cond
  File "C:\Users\win11\.conda\envs\omni\lib\site-packages\torch\_higher_order_ops\cond.py", line 5, in <module>
    import torch._subclasses.functional_tensor
  File "C:\Users\win11\.conda\envs\omni\lib\site-packages\torch\_subclasses\functional_tensor.py", line 42, in <module>
    class FunctionalTensor(torch.Tensor):
  File "C:\Users\win11\.conda\envs\omni\lib\site-packages\torch\_subclasses\functional_tensor.py", line 258, in FunctionalTensor
    cpu = _conversion_method_template(device=torch.device("cpu"))
C:\Users\win11\.conda\envs\omni\lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
Traceback (most recent call last):
  File "D:\mini-omni\server.py", line 6, in <module>
    from inference import OmniInference
  File "D:\mini-omni\inference.py", line 24, in <module>
    import whisper
  File "C:\Users\win11\.conda\envs\omni\lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
  File "C:\Users\win11\.conda\envs\omni\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

**Comment by tiandaoyuxi** [comment]
OS:win11

**Comment by zoldaten** [comment]
theres a problem with numpy or torch: UserWarning: Failed to initialize NumPy: _ARRAY_API not found 

which versions u use ?

*dont forget to start with python3 (not python)?

**Comment by mini-omni** [comment]
@zoldaten thanks for your help.
@tiandaoyuxi sorry, we only tested on the linux environment, and I'm not familier with DL settings for WinOS. But my suggestion will be: check the modules' version and make sure you run the right way.

**Comment by AgainstEntropy** [comment]
There are some hints in error info and [`requirements.txt`](https://github.com/gpt-omni/mini-omni/blob/ae04f9773344e94ed6485628f767dedd7e860f48/requirements.txt#L13) actually.
Try installing numpy with a version below 2:
```
pip install numpy<2
```

**Comment by mini-omni** [comment]
as @AgainstEntropy mentioned, you may try: `pip install numpy==1.26.3`, this numpy version works for me.

**Comment by pli2014** [comment]
pip install numpy==1.26.3 which resolve this issure.

**Comment by mini-omni** [comment]
I close it for now, feel free to re-open.
