### ISSUE TITLE
 Could I run on CPU on Mac pro?

### ISSUE THREAD

**Issue by Aaron-genai-superdev** [gpt-omni/mini-omni#23]
Dear,

When I am doing "python3 server.py --ip '0.0.0.0' --port 60808"
I face the problem of "AssertionError: Torch not compiled with CUDA enabled"
I am Mac pro on M2, could i run the mini-omnion CPU? thanks.

**Comment by BrenchCC** [comment]
> Dear,
> 
> When I am doing "python3 server.py --ip '0.0.0.0' --port 60808" I face the problem of "AssertionError: Torch not compiled with CUDA enabled" I am Mac pro on M2, could i run the mini-omnion CPU? thanks.

Maybe you need to modify ```inference.py``` and ```server.py``` to change ```device='cuda'``` to ```device='cpu'``` .

**Comment by BrenchCC** [comment]
But I get another bug, I only had deployed it on linux successfully.

**Comment by scalar27** [comment]
Discussed here:  https://github.com/gpt-omni/mini-omni/issues/6

**Comment by mini-omni** [comment]
> But I get another bug, I only had deployed it on linux successfully.

hi, @BrenchCC , what's the bug?

**Comment by BrenchCC** [comment]
```
C:\Users\10345\anaconda3\envs\omni\python.exe C:\pythoncode\mini-omni_deploy\mini-omni\server.py 
using LLAMA MLP adapter for ASR feature
Traceback (most recent call last):
  File "C:\pythoncode\mini-omni_deploy\mini-omni\server.py", line 56, in <module>
    fire.Fire(serve)
  File "C:\Users\10345\anaconda3\envs\omni\lib\site-packages\fire\core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\10345\anaconda3\envs\omni\lib\site-packages\fire\core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\10345\anaconda3\envs\omni\lib\site-packages\fire\core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\pythoncode\mini-omni_deploy\mini-omni\server.py", line 51, in serve
    OmniChatServer(ip, port=port, run_app=True)
  File "C:\pythoncode\mini-omni_deploy\mini-omni\server.py", line 17, in __init__
    self.client.warm_up()
  File "C:\pythoncode\mini-omni_deploy\mini-omni\inference.py", line 383, in warm_up
    for _ in self.run_AT_batch_stream(sample):
  File "C:\Users\10345\anaconda3\envs\omni\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\pythoncode\mini-omni_deploy\mini-omni\inference.py", line 404, in run_AT_batch_stream
    mel, leng = load_audio(audio_path)
  File "C:\pythoncode\mini-omni_deploy\mini-omni\inference.py", line 140, in load_audio
    audio = whisper.load_audio(path)
  File "C:\Users\10345\anaconda3\envs\omni\lib\site-packages\whisper\audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
  File "C:\Users\10345\anaconda3\envs\omni\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\10345\anaconda3\envs\omni\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\10345\anaconda3\envs\omni\lib\subprocess.py", line 1460, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```
Maybe it is about my system config problem.

**Comment by kunci115** [comment]
clone from the forked repo, I have run it on my mac, but seems whisper not doing transcription fluently, but atleast it work end to end
https://github.com/kunci115/mini-omni-mac-support

**Comment by Aaron-genai-superdev** [comment]
Guys, I change everthing to cpu , we need modify the inference.py , and  server.py, and the litgpt/model.py too. But the effect are not as good as i expected, the latency is too much on CPU(although i am Mac pro on M2, not bad).

**Comment by Aaron-genai-superdev** [comment]
> clone from the forked repo, I have run it on my mac, but seems whisper not doing transcription fluently, but atleast it work end to end https://github.com/kunci115/mini-omni-mac-support

thanks for you hard work, i forked and run on my mac, it works, but the latency could not be beared. Yes atleast it work end to end. And I do a pull request too, pls check.

**Comment by mini-omni** [comment]
I'll close it for now, please feel free to re-open.
