### ISSUE TITLE
windows11 下面启动python server.py --ip '0.0.0.0' --port 60808 出现下面的错误 或者说 ./checkpoint/lit_model.pth 去哪里下载

### ISSUE THREAD

**Issue by anstonjie** [gpt-omni/mini-omni#31]
Traceback (most recent call last):
  File "D:\ai3\mini-omni\server.py", line 56, in <module>
    fire.Fire(serve)
  File "D:\ai3\mini-omni\.venv\lib\site-packages\fire\core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\ai3\mini-omni\.venv\lib\site-packages\fire\core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "D:\ai3\mini-omni\.venv\lib\site-packages\fire\core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "D:\ai3\mini-omni\server.py", line 51, in serve
    OmniChatServer(ip, port=port, run_app=True)
  File "D:\ai3\mini-omni\server.py", line 16, in __init__
    self.client = OmniInference(ckpt_dir, device)
  File "D:\ai3\mini-omni\inference.py", line 380, in __init__
    self.fabric, self.model, self.text_tokenizer, self.snacmodel, self.whispermodel = load_model(ckpt_dir, device)
  File "D:\ai3\mini-omni\inference.py", line 361, in load_model
    state_dict = lazy_load(ckpt_dir + "/lit_model.pth")
  File "D:\ai3\mini-omni\.venv\lib\site-packages\lightning\fabric\utilities\load.py", line 203, in _lazy_load
    raise FileNotFoundError(f"Path {str(filename)!r} does not exist or is not a file.")
FileNotFoundError: Path './checkpoint/lit_model.pth' does not exist or is not a file.

**Comment by BrenchCC** [comment]
[https://huggingface.co/gpt-omni/mini-omni](url) 把这里的文件放入项目根目录下的checkpoint文件夹即可，这个项目需要三个模型文件，你可能需要查阅一下

**Comment by anstonjie** [comment]
谢谢

**Comment by mini-omni** [comment]
也可以尝试把 './checkpoint' 先删除或重命名，这样再执行时会自动从hf下载对应文件。

**Comment by DAAworld** [comment]
> [https://huggingface.co/gpt-omni/mini-omni](url) 把这里的文件放入项目根目录下的checkpoint文件夹即可，这个项目需要三个模型文件，你可能需要查阅一下

3个模型?
