### ISSUE TITLE
after recording voice from micro-phone, error 

### ISSUE THREAD

**Issue by taozhiyuai** [gpt-omni/mini-omni#49]
after recording voice from micro-phone, error 

`
(omni) taozhiyu@Mac ~ % API_URL=http://0.0.0.0:60808/chat python3 webui/omni_gradio.py
Running on local URL: http://127.0.0.1:7860
python3: can't open file '/Users/taozhiyu/webui/omni_gradio.py': [Errno 2] No such file or directory
zsh: command not found: Running
(omni) taozhiyu@Mac ~ % cd downloads
(omni) taozhiyu@Mac downloads % cd mini-omni 
(omni) taozhiyu@Mac mini-omni % API_URL=http://0.0.0.0:60808/chat python3 webui/omni_gradio.py
Running on local URL: http://127.0.0.1:7860
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
filepath: /private/var/folders/rd/0_kt6h0545g1v749gjmryqqr0000gn/T/gradio/44dbf90fa92b51404a87aa3d6d53462eba1fa670999133179ddd41ea61018231/audio.wav
Traceback (most recent call last):
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/connection.py", line 398, in request
    self.endheaders()
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/connection.py", line 236, in connect
    self.sock = self._new_conn()
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/connection.py", line 211, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11bbd07f0>: Failed to establish a new connection: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=60808): Max retries exceeded with url: /chat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11bbd07f0>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/gradio/route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/gradio/blocks.py", line 1532, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/gradio/utils.py", line 671, in async_iteration
    return await iterator.__anext__()
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/gradio/utils.py", line 664, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/gradio/utils.py", line 647, in run_sync_iterator_async
    return next(iterator)
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/gradio/utils.py", line 809, in gen_wrapper
    response = next(iterator)
  File "/Users/taozhiyu/Downloads/mini-omni/webui/omni_gradio.py", line 38, in process_audio
    with requests.post(API_URL, json=files, stream=True) as response:
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=60808): Max retries exceeded with url: /chat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11bbd07f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
`

**Comment by mini-omni** [comment]
please confirm that you started the server firstly.

**Comment by ucas010** [comment]
我也报这个错了，大佬解决了吗？

**Comment by mini-omni** [comment]
> > please confirm that you started the server firstly.
> 
> 怎么打开呢.我都是按readme操作的.

第一步是需要先启动server。如果成功了，启动gradio后，发送数据到server，会看到server会有log。可以看看你server侧的Log是什么。

**Comment by mini-omni** [comment]
I will close it for now, please feel free to re-open.
