### ISSUE TITLE
python3 server.py --ip '0.0.0.0' --port 60808的运行错误

### ISSUE THREAD

**Issue by taozhiyuai** [gpt-omni/mini-omni#50]
`(omni) taozhiyu@Mac mini-omni % python3 server.py --ip '0.0.0.0' --port 60808
Traceback (most recent call last):
  File "/Users/taozhiyu/Downloads/mini-omni/server.py", line 6, in <module>
    from inference import OmniInference
  File "/Users/taozhiyu/Downloads/mini-omni/inference.py", line 10, in <module>
    from litgpt.generate.base import (
  File "/Users/taozhiyu/Downloads/mini-omni/litgpt/generate/base.py", line 10, in <module>
    from utils.snac_utils import layershift, snac_config
ModuleNotFoundError: No module named 'utils.snac_utils'`

**Comment by pli2014** [comment]
pip install gradio==4.43.0 could resolve this issue.

**Comment by taozhiyuai** [comment]
> pip install gradio==4.43.0 could resolve this issue.

NO! same error

**Comment by mini-omni** [comment]
- error: `ModuleNotFoundError: No module named 'utils.xxxx'`
    Answer: run `export PYTHONPATH=./` first.

**Comment by mini-omni** [comment]
I'll close it for now, please feel free to re-open.

**Comment by pjxhhhh** [comment]
I run `pip uninstall utils` to resolve it

**Comment by alexhegit** [comment]
> * error: `ModuleNotFoundError: No module named 'utils.xxxx'`
>   Answer: run `export PYTHONPATH=./` first.

It is not work for me. Still same err log,

```
Traceback (most recent call last):
  File "/home/igpu/Demo/mini-omni2/server.py", line 6, in <module>
    from inference_vision import OmniVisionInference
  File "/home/igpu/Demo/mini-omni2/inference_vision.py", line 3, in <module>
    from litgpt.generate.base import next_token_image_batch
  File "/home/igpu/Demo/mini-omni2/litgpt/generate/base.py", line 10, in <module>
    from utils.snac_utils import layershift, snac_config
ModuleNotFoundError: No module named 'utils.snac_utils'
```

**Comment by mini-omni** [comment]
@alexhegit hi, I just updated the repo and tried to fix the import issue, please try again.
