### ISSUE TITLE
run webui/omni_streamlit.py failed with import name 'get_speech_timestamps' from 'utils' 

### ISSUE THREAD

**Issue by alexhegit** [gpt-omni/mini-omni#52]
(omni) alex@RyzerA:~/mini-omni$ pip list | grep utils
utils                     1.0.2
(omni) alex@RyzerA:~/mini-omni$ API_URL=http://0.0.0.0:60808/chat streamlit run webui/omni_streamlit.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.26.106.219:8501

2024-09-08 10:22:23.834 Uncaught app exception
Traceback (most recent call last):
  File "/home/alex/anaconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
  File "/home/alex/anaconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "/home/alex/mini-omni/webui/omni_streamlit.py", line 17, in <module>
    from utils import get_speech_timestamps, collect_chunks, VadOptions
ImportError: cannot import name 'get_speech_timestamps' from 'utils' (/home/alex/anaconda3/envs/omni/lib/python3.10/site-packages/utils/__init__.py)
2024-09-08 10:22:24.912 Uncaught app exception
Traceback (most recent call last):
  File "/home/alex/anaconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
  File "/home/alex/anaconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "/home/alex/mini-omni/webui/omni_streamlit.py", line 17, in <module>
    from utils import get_speech_timestamps, collect_chunks, VadOptions
ImportError: cannot import name 'get_speech_timestamps' from 'utils' (/home/alex/anaconda3/envs/omni/lib/python3.10/site-packages/utils/__init__.py)

**Comment by pli2014** [comment]
please use gradio webui. gradio==4.43.0 instead of compatible version.

**Comment by mini-omni** [comment]
you need to uninstall the module and run:
```
pip uninstall utils
export PYTHONPATH=./
 API_URL=http://0.0.0.0:60808/chat streamlit run webui/omni_streamlit.py
```

**Comment by mini-omni** [comment]
I'll close it for now, please feel free to re-open.
