### ISSUE TITLE
主界面录音结束后,出现错误,我的声音可以播放

### ISSUE THREAD

**Issue by taozhiyuai** [gpt-omni/mini-omni#54]
主界面录音结束后,出现错误,我的声音可以播放

网页的错误
`OSError: [Errno -9981] Input overflowed
Traceback:
File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
File "/Users/taozhiyu/Downloads/mini-omni/webui/omni_streamlit.py", line 258, in <module>
    main()
File "/Users/taozhiyu/Downloads/mini-omni/webui/omni_streamlit.py", line 243, in main
    recording(status)
File "/Users/taozhiyu/Downloads/mini-omni/webui/omni_streamlit.py", line 176, in recording
    audio_bytes = stream.read(IN_CHUNK)
File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/pyaudio/__init__.py", line 570, in read
    return pa.read_stream(self._stream, num_frames,`

终端命令行错误
`(omni) taozhiyu@Mac mini-omni % streamlit run webui/omni_streamlit.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.31.160:8501

  For better performance, install the Watchdog module:

  $ xcode-select --install
  $ pip install watchdog
            
warm up done, time_cost: 0.021 s
duration_after_vad: 0.512 s, time_vad: 0.509 s
2024-09-08 21:27:10.688 Uncaught app exception
Traceback (most recent call last):
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/taozhiyu/Downloads/mini-omni/webui/omni_streamlit.py", line 258, in <module>
    main()
  File "/Users/taozhiyu/Downloads/mini-omni/webui/omni_streamlit.py", line 243, in main
    recording(status)
  File "/Users/taozhiyu/Downloads/mini-omni/webui/omni_streamlit.py", line 176, in recording
    audio_bytes = stream.read(IN_CHUNK)
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/pyaudio/__init__.py", line 570, in read
    return pa.read_stream(self._stream, num_frames,
OSError: [Errno -9981] Input overflowed

`

**Comment by mini-omni** [comment]
我有时首次启动时会有提示`OSError: [Errno -9981] Input overflowed`这个问题，可以刷新或重新点击 Stop 再 Start 就可以正常运行。

**Comment by mini-omni** [comment]
I'll close it for now, please feel free to re-open.
