### ISSUE TITLE
Windows 11 ModuleNotFoundError: No module named 'lightning'

### ISSUE THREAD

**Issue by Kingbadger3d** [gpt-omni/mini-omni#58]
Has anyone created a version of this repo that works with windows yet, even though I have lightning install by Pip, Conda, ive tried all managers it still doesnt work:

(venv) D:\mini_omni\venv\Scripts\mini-omni>python3 server.py --ip '0.0.0.0' --port 60808
Traceback (most recent call last):
  File "D:\mini_omni\venv\Scripts\mini-omni\server.py", line 6, in <module>
    from inference import OmniInference
  File "D:\mini_omni\venv\Scripts\mini-omni\inference.py", line 2, in <module>
    import lightning as L
ModuleNotFoundError: No module named 'lightning'

**Comment by mini-omni** [comment]
Hi, did you install all the requirements in the tutorial?

**Comment by Kingbadger3d** [comment]
yeah The requirements ran fine no errors, but when you run it it complains about lightning not found, maybe the lib is broken right now or maybe it doesnt work on windows full stop ive not looked deeper as this happens all the time on windows. If you guys could try to get a windows version working i would love to have a play with this. Cheers

**Comment by mini-omni** [comment]
hi, @Kingbadger3d, you may check this PR, the author claimed work well with WinOS. https://github.com/kunci115/mini-omni-mac-support/tree/main

**Comment by mini-omni** [comment]
I will close it for now, please feel free to re-open.
