### ISSUE TITLE
How to solve the problem of not being able to access huggingface?

### ISSUE THREAD

**Issue by Donnie88** [gpt-omni/mini-omni#75]
python3 server.py --ip '0.0.0.0' --port 60808
checkpoint directory ./checkpoint not found, downloading from huggingface
Traceback (most recent call last):
  File "/home/lighthouse/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/home/lighthouse/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/lighthouse/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lighthouse/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/home/lighthouse/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/home/lighthouse/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/lighthouse/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/lighthouse/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
  File "/home/lighthouse/miniconda3/envs/omni/lib/python3.10/site-packages/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7c4471473e50>: Failed to establish a new connection: [Errno 101] Network is unreachable

**Comment by mini-omni** [comment]
hi, you may need a proxy to get better connection to huggingface and whisper checkpoint.

**Comment by monkeycc** [comment]
有大佬提供百度网盘吗，模型放网盘
