### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Btlmd** [gpt-omni/mini-omni#97]
I encountered CUDA error when trying to generate output. To debug it, I tried running
```bash
CUDA_LAUNCH_BLOCKING=1 python3 server.py --ip '0.0.0.0' --port 60808
```
and obtained the following traceback.

```python
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/serving.py", line 325, in execute
    for data in application_iter:
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/wsgi.py", line 256, in __next__
    return self._next()
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
  File "/usr/local/lib/python3.10/dist-packages/flask/helpers.py", line 113, in generator
    yield from gen
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "/workspace/mingdao/mini-omni/inference.py", line 502, in run_AT_batch_stream
    audio_stream = generate_audio_data(snac, self.snacmodel, self.device)
  File "/workspace/mingdao/mini-omni/utils/snac_utils.py", line 27, in generate_audio_data
    audio_hat = snacmodel.decode(audio)
  File "/usr/local/lib/python3.10/dist-packages/snac/snac.py", line 88, in decode
    z_q = self.quantizer.from_codes(codes)
  File "/usr/local/lib/python3.10/dist-packages/snac/vq.py", line 94, in from_codes
    z_p_i = self.quantizers[i].decode_code(codes[i])
  File "/usr/local/lib/python3.10/dist-packages/snac/vq.py", line 42, in decode_code
    return self.embed_code(embed_id).transpose(1, 2)
  File "/usr/local/lib/python3.10/dist-packages/snac/vq.py", line 39, in embed_code
    return F.embedding(embed_id, self.codebook.weight)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 2264, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

I also tried to print out the `audio` variable which caused the error.

```python
[tensor([[3195, 3453, 3680, 2107]], device='cuda:0'), tensor([[2481, 3046, 1893, 2919, 1120, 2702,  829, 2838]], device='cuda:0'), tensor([[3226, 2079, 22
67, 2870, 4019, 4060, 1102, 1798, 3992, 1960, 2267, 3823,
         3097, 3097,  688, 4097]], device='cuda:0')]
```

Can someone help to fix this?

**Comment by superFilicos** [comment]
sorry，这个是模型的预测时出了一些不稳定的问题，您可以把输出的audio Index限制在0 - 4096范围里，否则替换成0。
